class WidgetIDs:
    PATH_BAR_ID = "path-bar"
    BUCKET_LIST_ID = "bucket-list"
    OBJECT_LIST_ID = "object-list"
    MAIN_CONTAINER_ID = "main-container"
    CONTENT_AREA_ID = "content-area"
    BUCKET_PANEL_ID = "bucket-panel"
    BUCKET_HEADER_ID = "bucket-header"
    CONTENT_PANEL_ID = "content-panel"
    CONTENT_HEADER_ID = "content-header"
